<?php 

$texte="
<div class=WordSection1>

<p class=MsoNormal style='margin-bottom:6.0pt'><b><span style='font-size:14.0pt;
font-family:\"Calibri\",\"sans-serif\";text-transform:uppercase'>Actualités</span></b></p>

<p class=MsoNormal style='margin-bottom:6.0pt'><b><span style='font-size:18.0pt'>&nbsp;</span></b></p>

<p class=MsoNormal><u><span style='font-size:12.0pt;font-family:\"Times\",\"serif\";
text-transform:uppercase'>&#9830; Consortium Meeting de fin de Projet</span></u></p>

<p class=MsoNormal style='margin-bottom:12.0pt'><b><span style='font-size:11.0pt'>où:
</span></b><span style='font-size:11.0pt'>AGI, Suresnes<br>
<b>quand: </b>20 avril 2017<br>
<b>qui: </b>tous les partenaires</span></p>

<p class=MsoNormal><u><span style='font-size:12.0pt;font-family:\"Times\",\"serif\";
text-transform:uppercase'>&#9830; Soutenance de thèse de Floran Tostain</span></u></p>

<p class=MsoNormal style='margin-bottom:12.0pt'><b><span style='font-size:11.0pt'>où:
</span></b><span style='font-size:11.0pt'>ICA, Toulouse<br>
<b>quand: </b>2 décembre 2016<br>
<b>qui: </b>tous partenaires invités</span></p>

<p class=MsoNormal><u><span style='font-size:12.0pt;font-family:\"Times\",\"serif\";
text-transform:uppercase'>&#9830; Consortium Meeting T0+36</span></u></p>

<p class=MsoNormal style='margin-bottom:12.0pt'><b><span style='font-size:11.0pt'>où:
</span></b><span style='font-size:11.0pt'>IMPETUS, Grenade sur Garonne<br>
<b>quand: </b>5 juillet 2016<br>
<b>qui: </b>tous les partenaires</span></p>

<p class=MsoNormal><u><span style='font-size:12.0pt;font-family:\"Times\",\"serif\";
text-transform:uppercase'>&#9830; Consortium Meeting T0+30</span></u></p>

<p class=MsoNormal style='margin-bottom:12.0pt'><b><span style='font-size:11.0pt'>où:
</span></b><span style='font-size:11.0pt'>Holo3, St Louis<br>
<b>quand: </b>16 novembre  2015<br>
<b>qui: </b>tous les partenaires</span></p>

<p class=MsoNormal><u><span style='font-size:12.0pt;font-family:\"Times\",\"serif\";
text-transform:uppercase'>&#9830; Colloque mi-parcours ANR MatetPro</span></u></p>

<p class=MsoNormal style='margin-bottom:12.0pt'><b><span style='font-size:11.0pt'>où:</span></b><span
style='font-size:11.0pt'><br>
<b>quand: </b>20 et 21 mai 2015<br>
<b>qui: </b>AGI</span></p>

<p class=MsoNormal><u><span style='font-size:12.0pt;font-family:\"Times\",\"serif\";
text-transform:uppercase'>&#9830; Consortium Meeting T0+24</span></u></p>

<p class=MsoNormal style='margin-bottom:12.0pt'><b><span style='font-size:11.0pt'>où:
</span></b><span style='font-size:11.0pt'>I2M, Bordeaux<br>
<b>quand: </b>21 avril 2015<br>
<b>qui: </b>tous les partenaires</span></p>

<p class=MsoNormal><u><span style='font-size:12.0pt;font-family:\"Times\",\"serif\";
text-transform:uppercase'>&#9830; Consortium Meeting T0+18</span></u></p>

<p class=MsoNormal style='margin-bottom:12.0pt'><b><span style='font-size:11.0pt'>où:
</span></b><span style='font-size:11.0pt'>ICA, Toulouse<br>
<b>quand: </b>21 octobre 2014<br>
<b>qui: </b>tous les partenaires</span></p>

<p class=MsoNormal><u><span style='font-size:12.0pt;font-family:\"Times\",\"serif\";
text-transform:uppercase'>&#9830; Consortium Meeting T0+12</span></u></p>

<p class=MsoNormal style='margin-bottom:12.0pt'><b><span style='font-size:11.0pt'>où:
</span></b><span style='font-size:11.0pt'>ONERA, Lille<br>
<b>quand: </b>12 mars 2014<br>
<b>qui: </b>tous les partenaires</span></p>

<p class=MsoNormal><u><span style='font-size:12.0pt;font-family:\"Times\",\"serif\";
text-transform:uppercase'>&#9830; Workshop à AGI</span></u></p>

<p class=MsoNormal style='margin-bottom:12.0pt'><b><span style='font-size:11.0pt'>où:
</span></b><span style='font-size:11.0pt'>AGI, Toulouse<br>
<b>quand: </b>16 janvier 2014<br>
<b>qui: </b>tous les partenaires</span></p>

<p class=MsoNormal><u><span style='font-size:12.0pt;font-family:\"Times\",\"serif\";
text-transform:uppercase'>&#9830; Consortium Meeting T0+6</span></u></p>

<p class=MsoNormal style='margin-bottom:12.0pt'><b><span style='font-size:11.0pt'>où:
</span></b><span style='font-size:11.0pt'>LMT, Cachan<br>
<b>quand: </b>24 septembre 2013<br>
<b>qui: </b>tous les partenaires</span></p>

<p class=MsoNormal><u><span style='font-size:12.0pt;font-family:\"Times\",\"serif\";
text-transform:uppercase'>&#9830; Kickoff Meeting</span></u></p>

<p class=MsoNormal style='margin-bottom:12.0pt'><b><span style='font-size:11.0pt'>où:
</span></b><span style='font-size:11.0pt'>AGI, Suresnes<br>
<b>quand: </b>5 avril 2013<br>
<b>qui: </b>tous les partenaires</span></p>

</div> ";

?>
