<?php 


$texte="<div class=WordSection1>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
style='font-size:14.0pt;font-variant:small-caps'>Publications liées au projet
VulComp2</span></b></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=EN-US>&nbsp;</span></b></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><u><span
lang=EN-US style='font-size:12.0pt;font-variant:small-caps'>Articles</span></u></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=ES>H.A. Israr Ahmad, S. Rivallant, J.-J. Barrau</span></b><span lang=ES>. </span><span
lang=EN-US>Experimental investigation on mean crushing stress characterization
of carbon-epoxy plies under compressive crushing mode. <i>Composite Structures.</i>
Vol. 96, pp. 357-364 (2013)</span></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=EN-US>Allix O</span></b><span lang=EN-US>. The bounded rate concept: A
framework to deal with objective failure predictions in dynamic within a local
constitutive model. <i>IJDM</i> 22 -6, pp 808-828 (2013)</span></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b>O Allix, N
Feld, E Baranger, JM Guimard, C Ha-Minh</b>. <span lang=EN-US>The compressive
behaviour of composites including fiber kinking: modelling across the scales. <i>MECCANICA</i>&nbsp;
Volume: 49:2571-2586 (2014)</span></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=EN-US>H.A. Israr Ahmad, S. Rivallant, C. Bouvet, J.-J. Barrau</span></b><span
lang=EN-US>. Finite Element simulation of 0°/90° CFRP laminated plates
subjected to crushing using a free-face-crushing concept. <i>Composites Part A:
Applied Science and Manufacturing.</i> Vol. 62, pp. 16-25 (2014)</span></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=EN-US>J. Girardot, F. Dau</span></b><span lang=EN-US>. A mesoscopic model
using the Discrete Element Method for impacts on dry fabrics <i>Matériaux et
Techniques</i>, vol. 104 (2016)</span></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b>JS.
Affagard, F. Mathieu, JM. </b><b><span lang=EN-US>Guimard, F. Hild</span></b><span
lang=EN-US>. Identification method for the mixed mode interlaminar behavior of
a composite thermoset using displacement field measurements and load data. </span><i>Composites
Part A</i>, pp 238-249 (2016)</p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=EN-US>&nbsp;</span></b></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><u><span
lang=EN-US style='font-size:12.0pt;font-variant:small-caps'>Ouvrages</span></u></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=EN-US>S. Jaminion</span></b><span lang=EN-US>, Participation à la
rédaction du livre : «&nbsp;Composite Materials Design and Testing&nbsp;,
Unlocking mystery with invariants», by S.W.Tsai and J.D.D. Melo , 2015</span></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=EN-US>&nbsp;</span></b></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><u><span
lang=EN-US style='font-size:12.0pt;font-variant:small-caps'>Conférences
Plénières</span></u></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b>O. Allix</b>.
Modélisation mésoscopique des stratifiés: vers la prédiction de l'absorption
d'énergie. <i>19éme Journées Nationales &nbsp;des Composites</i>, Lyon Juillet
2015</p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=EN-US>O. Allix</span></b><span lang=EN-US>. Damage and failure of
laminates: from statics to dynamics ? <i>Congress on Numerical Methods in Engineering,
CMN2015</i>, Lisbon Juillet 2015</span></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><span
lang=EN-US>&nbsp;</span></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><u><span
lang=EN-US style='font-size:12.0pt;font-variant:small-caps'>Conférences
invitées internationales</span></u></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=EN-US>O. Allix</span></b><span lang=EN-US>.&nbsp; &quot;On bounded rate
constitutive model: application to objective failure prediction&quot; , <i>IUTAM
SYMPOSIUM ON MATERIALS AND INTERFACES UNDER HIGH STRAIN RATE AND LARGE DEFORMATION</i>
June 17-21, 2013, Metz, France</span></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=EN-US>S. Jaminion</span></b><span lang=EN-US>. A new analysis of Laminate
with the software Correli<sup>STC</sup>. <i>Composites Durability Workshop 19</i>;
July 27-29 2014, Stanford University, California</span></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=EN-US>O. Allix</span></b><span lang=EN-US>. The compressive behavior of
composites including fragmentation: modeling across the scales, <i>IUTAM
Symposium on Connecting Multiscale Mechanics to Complex Material Design</i>,
September, 2014, Chicago, USA</span></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><span
lang=EN-US>&nbsp;</span></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><u><span
lang=EN-US style='font-size:12.0pt;font-variant:small-caps'>Conférences
internationales</span></u></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=EN-US>E. Baranger, J. Lopez, O. Allix, N. Feld , J. M. Guimard, C. Ha Minh</span></b><span
lang=EN-US>. Multiscale modeling of kinking in CFRPs: validation and
competition between mechanisms, <i>CFRAC-2013</i>, Prague Juin 2013</span></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=EN-US>S. Jaminion</span></b><span lang=EN-US>. Strain measurement on the
entire surface with the software Correli<sup>STC</sup>. <i>JEC Europe 2014
Conference</i>, March 11-13 2014</span></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=EN-US>N. Feld, O. Allix, E. Baranger, J.M. Guimard, C. Ha Minh</span></b><span
lang=EN-US>. Multiscale modeling of the compressive behaviour of CFRP
structures: <i>16<sup>th</sup> European Conference on Composite Materials, ECCM</i>,
June 2014 Seville, Spain</span></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=EN-US>S. Jaminion</span></b><span lang=EN-US>. Correli<sup>STC</sup>:
Software for a Digital Image Correlation (DIC) using a global approach. <i>JEC
Europe 2015 Conference</i>, March 10-12 2015</span></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=EN-US>J. Girardot, F. Dau</span></b><span lang=EN-US>. Modeling dry
fabrics under impact with a 3D discrete element method <i>Proc. in ICCS</i>,
20/07/2015</span></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=EN-US>F. Tostain, C. Espinosa and S. Rivallant</span></b><span lang=EN-US>.
Crushing of aeronautical composite absorbers using canonical and
phenomenological ruin criteria. <i>Proceedings of V ECCOMAS Thematic Conference
on the Mechanical Response of Composites</i>, Bristol, UK, 7-9 September 2015</span></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=EN-US>S. Jaminion, J. W. Nelson</span></b><span lang=EN-US>. Utilization
of Correli<sup>STC</sup> digital image correlation software to characterize
multi scale composite  material and structural responses. <i>JEC America 2016</i>,
Atlanta, Conférence May 2-5 2016</span></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=ES>F. Tostain, P. Guillén Ulecia, L. Fúster Alfonso, S. Rivallant and C.
Espinosa</span></b><span lang=ES>. </span><span lang=EN-US>Experimental
investigation of crushed composite plates under static and dynamic loads. <i>Proceedings
of ICILSM 2016 - 1st International Conference on Impact Loading of Structures
and Materials</i>, Turin, Italie, 22-26 May 2016</span></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=EN-US>C. Espinosa, F. Tostain, S. Rivallant</span></b><span lang=EN-US>.
Stabilization of the numerical priming to stabilization phenomenon in the
crushing of a composite panel using local and diffuse damage laws, <i>ECCOMAS
Congress 2016</i>, Crete Island, Greece, 5--10 June 2016</span></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><span
lang=EN-US>&nbsp;</span></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><u><span
lang=EN-US style='font-size:12.0pt;font-variant:small-caps'>Conférences
Nationales</span></u></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=EN-US>F. Tostain, C. Espinosa and S. Rivallant</span></b><span lang=EN-US>.
</span>Absorption dénergie: un modèle de fragmentation diffuse et localisée pour
le crash de composite carbone/epoxy<i>. Proceedings of CSMA - 12ème Colloque
National en Calcul des Structures</i>, Giens, France, 18-22 mai 2015</p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b>J. Berthe,
G. Portemont, A. Deudon</b>. Essais dynamiques de matage sur composites avec
mesure des champs de déplacement et de température. <i>JNC</i>, Lyon, 2015</p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=EN-US>J. Girardot, F. Dau.</span></b><span lang=EN-US> Modeling dry
fabrics under impact with a 3D discrete element method Proc. in <i>JNC</i>,
29/06/2015</span></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=EN-US>S. Rivallant, A. Gonzalez, F. Tostain, C. Espinosa</span></b><span
lang=EN-US>. </span>Etude des débris générés lors de lécrasement de stratifiés
CFRP<span lang=EN-US>. <i>JNC20</i>, Champs sur Marne, 28-30 juin 2017</span></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><span
lang=EN-US>&nbsp;</span></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><u><span
lang=EN-US style='font-size:12.0pt;font-variant:small-caps'>Workshops</span></u></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=EN-US>O. Allix</span></b><span lang=EN-US>. &quot; Damage and failure of
laminates in dynamics some progresses and open challenges&quot;, <i>Journées
Dynrap 2015</i>, DGA-Balma, Mars 2015</span></p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b>J. Limido</b>.
«&nbsp;Approche innovante pour la modélisation d'explosion en champ proche et
fragmentation&nbsp;» &quot;, <i>Journées Dynrap 2015</i>, DGA-Balma, Mars 2015</p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=EN-US>F. Tostain, C. Espinosa and S. Rivallant</span></b><span lang=EN-US>.
</span>Modèles d'écrasement localisé et d'endommagement diffus pour la
simulation du crash de structures composites. <i>Journées Thématiques DynRap
'Etudes de phénomènes en dynamique rapide par essais et simulations'</i>, DGA -
Techniques aéronautiques, Toulouse, France, 25-26 mars 2015</p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b>J. Limido.</b>
«&nbsp;Vulnérabilité des composites: Fragmentation dynamique&nbsp;», <i>Journée
Simulation AEROSPACEVALLEY DAS AMP</i>, Agropole -- Agen, 10 Juin 2015</p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b>C. Espinosa,
F. Tostain, S. Rivallant</b>. Modélisation des ruptures et fragmentations
dynamiques de stratifiés composites en écrasement. <i>Journées du groupe de
travail MÉCADYMAT comportement et rupture des matériaux sous sollicitations
dynamiques, </i>Strasbourg -- 30 &amp; 31 mars 2016</p>

<p class=MsoNormal style='margin-bottom:6.0pt;line-height:normal'><b><span
lang=EN-US>J. Girardot, F. Dau</span></b><span lang=EN-US>. Modeling a textile
at different scales using the DEM Application to impact <i>Proc. in Euromech
colloquium 569</i>, 05/04/2016</span></p>

</div>

";
?>
