<?php 

$texte="
<h1> News</h1>
<br><br>";
$texte.="

<h3>&#9830; Audit à mi-parcours</h3>
<b>où:</b> ANR, Paris, Fr.<br>
<b>quand:</b> 18th december 2014<br>
<b>qui :</b> Porteur du projet et responsables locaux 
<br><br>


<h3>&#9830; Réunion de consortium à Nantes</h3>
<b>où:</b> GeM, Ecole Centrale de Nantes, Fr.<br>
<b>quand:</b> 13 octobre 2014<br>
<b>qui :</b> tous.
<br><br>

<h3>&#9830; Dissémination du Projet </h3>
<b>title:</b> Merging Software Capabilities: the non-intrusive path <br>
<b>journal:</b> ECCOMAS newsletter<br>
<b>Issue</b> July 14, <b>Pages</b> 8-12<br> 
<a href=\"http://www.eccomas.org/Fichs/DisplayFich?fichName=/cvdata/cntr1/spc22/dtos/dcs/Newsletter-July2014.pdf\" target=\"_blank\"><img src=\"eccomas.png\" width=150 border=0></a>
<br><br>


<h3>&#9830; Videoconference</h3>
<b>quand:</b> 26 juin 2014 à 14h<br>
<b>qui :</b> tous les partenaires.
<br><br>

<h3>&#9830; Dissémination du Projet </h3>
<b>title:</b> An innovative framework <br>
<b>journal:</b> international innovation<br>
<b>Issue</b> 136, <b>Pages</b> 56-58<br> 
<a href=\"http://www.research-europe.com/magazine/ISSUE/136/index.html\" target=\"_blank\"><img src=\"intinnov.png\" width=400 border=0></a>
<br><br>

<h3>&#9830; Réunion technique chez EdF</h3>
<b>où:</b> EdF, Clamart, Fr.<br>
<b>quand:</b> 21 jan 2014<br>
<b>qui :</b> tous les partenaires.
<br><br>


<h3>&#9830; Réunion de consortium à Cachan</h3>
<b>où:</b> LMT, ENS-CACHAN, Cachan, Fr.<br>
<b>quand:</b> 25 septembre 2013<br>
<b>qui :</b> tous les partenaires.
<br><br>


<h3>&#9830; Kickoff meeting à Suresnes</h3>
<b>où:</b> EADS IW, Suresnes, Fr.<br>
<b>quand:</b> 17 et 18 jan 2013<br>
<b>qui :</b> tous les partenaires.
<br><br>";


?>
