<?php 


$texte="<h1> Publications in International peer reviewed journals</h1><hr><br>

<h3>2014</h3>
<b>G. Guguin, O. Allix, P. Gosselet, S. Guinard. </b>
Non intrusive coupling between 3D and 2D laminated composite models based on finite element 3D recovery.
<i>International Journal for Numerical Methods in Engineering.</i> 
Vol. 98, Num. 5, pp. 324-343, <b> 2014</b> 
DOI: <a href=\"http://dx.doi.org/10.1002/nme.4630\">10.1002/nme.4630</a><br>

<b>M. Duval, J.C. Passieux, M. Salaun, S. Guinard. </b>
Non-intrusive coupling: recent advances and scalable nonlinear domain decomposition. 
<i>Archives of Computational Methods in Engineering.</i> In Press. <b> 2014</b> 
DOI: <a href=\"http://dx.doi.org/10.1007/s11831-014-9132-x\">10.1007/s11831-014-9132-x</a><br>

<br><h3>2013</h3>

<b>M. Chevreuil, , A. Nouy, E. Safatly. </b>
A multiscale method with patch for the solution of stochastic partial differential equations with localized uncertainties. 
<i>Computer Methods in Applied Mechanics and Engineering.</i> 
Num. 255 pp. 255-274. <b> 2013</b> 
DOI: <a href=\"http://dx.doi.org/10.1016/j.cma.2012.12.003\">10.1016/j.cma.2012.12.003</a><br>

<b>J.C. Passieux, J. R&eacute;thor&eacute;, A. Gravouil and M.C. Baietto. </b>
Local/global non-intrusive crack propagation simulation using a multigrid X-FEM solver. 
<i>Computational Mechanics.</i> Vol. 52 Num. 6 pp. 1381-1393. <b> 2013</b> 
DOI: <a href=\"http://dx.doi.org/10.1007/s00466-013-0882-3\">10.1007/s00466-013-0882-3</a><br>

<br><br>
<h1> Conferences</h1><hr><br>
<h3>2014</h3>
<b>M. Duval, J.-C. Passieux, M. Salaün, S. Guinard</b>
Local/Global Non-Intrusive Parallel Coupling For Large Scale Mechanical Analysis
<i>proc. of WCCM XI, Barcelone, 20-25/07/2014</i> <br>

<b>G. Drouet, P. Hild.</b>
A Local optimal contact condition in 2D and 3D
<i>proc. of WCCM XI, Barcelone, 20-25/07/2014</i><br>

<b>G. Guguin, O. Allix, P. Gosselet, S. Guinard.</b>
A non-intrusive global-local approach for the coupling of laminated plates and 3D models.
<i>WCCM XI - 11th World Congress on Computational Mechanics. 2014.</i><br>

<b>M. Duval, J.-C. Passieux, M. Salaün and S. Guinard.</b>
Non Intrusive model coupling: A flexible way to handle local geometric and mechanical details in FEA.
<i>Proceedings of Joint conference on Mechanical, Design Engineering & Advanced Manufacturing (Toulouse, France), 2014</i><BR>

<b>J.-C. Passieux, A. Gravouil, J. Réthoré and M.-C. Baietto.</b> 
A localized multigrid nonintrusive coupling approach for mixed mode crack propagation. 
<i>42e Congrès National d'Analyse Numérique, CANUM 2014 (Carry-le-Rouet, France) 2014</i><br>


<br>
<h3>2013</h3>

<b>P. Gosselet, G. Guguin, O. Allix.</b>
Efficient non-intrusive coupling technique, with application to the analysis of the delamination of thin composite structures.
<i>V Conference on Computational Methods for Coupled Problems in Science and Engineering (COUPLED 2013), 2013.</i><br>

<b>G. Guguin, O. Allix, P. Gosselet.</b> 
Techniques de raccord 2D-3D pour l'analyse non-intrusive de structures composites stratifiées
<i>Colloque Nationale En Calcul des Structures, CSMA 2013</i><br>

<b>G. Guguin, O. Allix, P. Gosselet.</b>
A fictitious-like domain approach for the non-intrusive coupling between 2D and 3D models
<i>XFEM 2013 International Conference on Extended Finite Element Methods. 2013 </i><br>

<b>J.-C. Passieux, J. Réthoré, A. Gravouil and M.-C. Baietto.</b>
A local/global non-intrusive coupling approach for localized crack growth simulation
<i>International Conference on Extended Finite Element Methods - XFEM 2013 (Lyon, France), keynote lecture 2013</i><br>


<b>F. Pled, M. Chevreuil, A. Nouy.</b> 
Multiscale method with patches for the propagation of localized uncertainties in stochastic models. 
<i>International Conference on Extended Finite Element Methods - XFEM 2013 (Lyon, France), keynote lecture 2013</i><br>







<br><br>
<h1> Projet dissemination</h1><hr><br>

<b>Merging Software Capabilities: the non-intrusive path </b> 
in <i>ECCOMAS newsletter</i> 
July 14, pp. 8-12<br> 
<a href=\"http://www.eccomas.org/Fichs/DisplayFich?fichName=/cvdata/cntr1/spc22/dtos/dcs/Newsletter-July2014.pdf\" target=\"_blank\"><img src=\"eccomas.png\" width=150 border=0></a><br><br>

<b>An innovative framework </b> 
in <i> International Innovation</i> 
Num. 136, pp. 56-58 <br> 
<a href=\"http://www.research-europe.com/magazine/ISSUE/136/index.html\" target=\"_blank\"><img src=\"intinnov.png\" width=400 border=0></a> <br><br>

<br><br>
<h1> Downloadable Tools</h1><hr>
<br>A Message Passing Interface (MPI) framework for non-intrusive coupling [Duval et al. ACME 2014]<br>
<a href=\"http://ica.preprod.lamp.cnrs.fr/projets/icare/code.zip\" target=\"_blank\"><img src=\"zip.png\" width=52 border=0></a>";

?>
