<?php 

$texte="
<h1> LA SUITE : LE PROJET VIRTUOSE </h1><BR><BR>

<br><BR>

Au bilan l’ANR VERTEX a validé les concepts d’essais structuraux multiaxiaux proposés ainsi qu’une démarche très originale de dialogue essais/calculs. Les essais sont bien sur plus complexes de nature mais apportent aussi plus de valeurs ajouté. Un concept de validation par essais enveloppe a aussi été testé en fin d’ANR. L’idée est de parcourir un chemin d’effort à l’intérieur d’une enveloppe définit dans le cadre de vertex par les points expérimentaux obtenus. Le ratio est défini à partir des coefficients d’abattement utilisés en aéronautique (Valeurs B, Impact, Vieillissement, Charges Extremes et Limites ). Si la structure suit ce chemin d’effort sans endommagements, elle est validée. <br><br>

<div align=\"center\"> <img src=\"envols1.png\" height=314></div><BR><BR>

Une première analyse tomographique a effectivement été réalisée en pointe de fissure et aucun endommagement n’a été détecté. 
La recherche sur cette thématique continue via le projet VIRTUOSE (Virtual Testing of Aeronautical Composite Structures) financé par la Fondation Lopez-Loreta pour l’excellence académique. Le projet est porté par J. Serra et une présentation du projet est disponible : https://websites.isae-supaero.fr/virtuose/.
La prochaine étape, proposée dans le projet VIRTUOSE est de remplacer les points expérimentaux par des points calculés 

<div align=\"center\"> <img src=\"image444.png\" height=314></div><BR><BR>

De cette manière, il sera possible de simplifier de manière significative la pyramide des essais actuels. Ce serait une étape significative vers le Predictive Virtual Testing. 

<div align=\"center\"> <img src=\"image555.png\" height=314></div><BR><BR>




<br><br>";



?>
