<?php 

$texte=" <h1>Partenaires de VERTEX</h1>
Qualification, rôle et implication<br><br>";

$texte.="<img src=\"logo_airbus.jpg\" height=80><br>
AIRBUS GROUP Innovations est l’Unité de Recherche et Technologie (R&T) du Groupe AIRBUS. Avec des sites basés en France, en Allemagne, en Angleterre, en Espagne, en Russie, à Singapour, en Chine, en Inde et en Malaisie, représentant un réseau de plus de 700 personnes, il fournit des capacités de recherche d’envergure mondiale dans les secteurs de l’aéronautique, de la défense et de l’espace. En accord avec la stratégie R&T du groupe AIRBUS et couvrant les qualifications et domaines technologiques d’importance critique pour le Groupe, AIRBUS GROUP Innovations est organisé en sept centres techniques transnationaux :<br>
<br>
- Les Technologies Composites<br>
- Les Technologies Métalliques et l’Ingénierie des Surfaces<br>
- L'Ingénierie des Structures, Production et Aéromécanique<br>
- Les senseurs, l’Electronique et l’Intégration des Systèmes<br>
- Ingénierie, Physique, Technologies de l’information, Sécurité & Simulation<br>
- Energie & Propulsion<br>
- Concepts & Scenarios Innovants<br>
<br>
AIRBUS GROUP Innovations est l’entité à la fois stratégique et opérationnelle visant à promouvoir la création de valeur ajoutée par l’innovation, les compétences et la collaboration entre les différents membres du Groupe. Il favorise l’excellence technologique et oriente la stratégie de marché par le partage de ses compétences entre les divers partenaires du groupe AIRBUS et par le développement de partenariats avec les écoles, les universités et les centres de recherche au niveau international.

<br>
<br>
<br>
<img src=\"logo_lmt.jpg\" height=80><br>

<br>
<br>
<br>
<a href=\"http://www.institut-clement-ader.fr\"><img src=\"logo_ica.jpg\" height=80 border=0></a><br>
L'Institut Clément Ader est un jeune laboratoire de recherche (1) qui oeuvre principalement dans le domaine de la Mécanique du Solide, les sous domaines les plus représentatifs étant ceux des Matériaux, des Structures, des Systèmes, des Procédés et de la Mesure. Les applications visées sont principalement celles des secteurs de l’aéronautique et du spatial, mais également du transport et de l'énergie, plus généralement ceux des industries mécaniques. Ses activités sont centrées sur la modélisation du comportement des matériaux et des structures, et l'étude de leur durabilité. Il s'attache à couvrir à la fois, dans un juste équilibre, les approches théoriques, numériques et expérimentales. Une part importante de ses recherches sont relatives aux matériaux composites qui sont aujourd'hui incontournables dans le secteur aérospatial. C’est à ce titre, avec une compétence reconnue dans l’expertise au niveau structures que l’Institut Clément Ader est coordinateur de cette ANR. <br><br>
(1) L'ICA est issu, le 30 juin 2009, du rapprochement de trois structures de recherche en Midi-Pyrénées: le Centre de Recherche Outillages, Matériaux et Procédés de l'ENSTIMAC (CROMeP), le Département Mécanique Structures et Matériaux de l'ISAE (DMSM) et le Laboratoire de Génie Mécanique de Toulouse de l'INSA et de l'UPS (LGMT).

<br>
<br>
<br>
<img src=\"logo_holo3.bmp\" height=80><br>
HOLO3 est un centre de transfert de technologie spécialisé dans le développement de techniques optiques de mesure. La vocation du centre est de développer de nouveaux procédés basés sur des techniques optiques et de les transférer dans l'industrie. Cela passe par des projets de recherche, des études de faisabilité, des prestations de mesure ainsi que la conception / réalisation d'équipement industriel complets. Les développements réalisés trouvent des applications dans de nombreux secteurs industriels, et en premier lieu dans les secteurs de l'automobile, de l'aéronautique et dans le secteur médical.<br>
Les principales technologies développées par le centre sont les suivantes :<br>
- Interférométrie de speckle : applications dans l’analyse vibratoire et la mesure très fine de déformation<br>
- Lumière structurée : procédé de numérisation 3D d’objets pour du contrôle ou du reverse engineering<br>
- Corrélation d’image : technique de mesure des champs de déplacements et déformation de pièces sollicitées sur machine d’essai<br>
- Réalité Virtuelle : mise en oeuvre d’une plateforme pour la revue de projets, l’apprentissage,... <br>
- Déflectométrie : applications en métrologie des surfaces brillantes (vitrages, lentilles,...) et en analyse rapide de surface (rugosité, texture, réflectance,..)<br>
- Techniques d’imagerie spécifiques : infrarouge, multispectrale, imagerie de polarisation, ...<br>
Dans le cadre du projet HOLO3 développera des nouvelles fonctionnalités dans le logiciel CORRELISTC.

<br>
<br>
<br>
<img src=\"logo_lms.jpg\" height=80><br>

<br>
<br>
<br>
<img src=\"logo_onera.png\" height=80><br>


";



?>
