<?php 

$texte="
<h1> PERSPECTIVES : VERS LE PROJET ENVOLS </h1><BR><BR>

Au bilan l’ANR VERTEX a validé les concepts d’essais structuraux multiaxiaux proposés ainsi qu’une démarche très originale de dialogue essais/calculs. Les essais sont bien sur plus complexes de nature mais apportent aussi plus de valeurs ajouté. Un concept de validation par essais enveloppe a aussi été testé en fin d’ANR. L’idée est de parcourir un chemin d’effort à l’intérieur d’une enveloppe définit dans le cadre de vertex par les points expérimentaux obtenus. Le ratio est défini à partir des coefficients d’abattement utilisés en aéronautique (Valeurs B, Impact, Vieillissement, Charges Extremes et Limites ). Si la structure suit ce chemin d’effort sans endommagements, elle est validée. <br><br>

<div align=\"center\"> <img src=\"envols1.png\" height=314></div><BR><BR>

Une première analyse tomographique a effectivement été réalisée en pointe de fissure et aucun endommagement n’a été détecté. La prochaine étape, proposée dans l’ANR ENVOLS, déposée cette année est de remplacer les points expérimentaux par des points calculés. <br><br>

<div align=\"center\"> <img src=\"envols2.png\" height=314></div><BR><BR>

De cette manière, il sera possible de simplifier de manière significative la pyramide des essais actuelles. Ce serait une étape significative vers le Predictive Virtual Testing. L’ANR ENVOLS reprend le même consortium que VERTEX mais avec aussi Airbus Safran Launchers et probablement Airbus Avion qui ont participé au comité de suivi de VERTEX et souhaitent s’impliquer dans cette nouvelle aventure qui rejoint leurs feuilles de route R&D.<br><br>

<div align=\"center\"> <img src=\"envols3.png\" height=314></div><BR><BR>




<br><br>";



?>
