<?php 

$texte="
<h1> Réunions VERTEX</h1>
<BR>
&#9830; Kick-off Meeting VERTEX : 31/01/2013 à l’Institut Clément ADER/ISAE.<BR>
&#9830; 20/02/2013 : Lancement du Programme Matetpro<BR>
&#9830; Réunion T0+6 : 18/07/2013 à l’Institut Clément ADER<BR>
&#9830; 01/09/2013 : Débuts des thèses de Joël Serra, Jean-Emmanuel Pierré et Hadrien Bainier<BR>
&#9830; Séminaire VERTEX : les 6 et 7 Février 2014 à AIRBUS GROUP INNOVATION à Suresnes<BR>
&#9830; Réunion T0+24 Avec Comité de Suivi : 30/01/2015 à l’Institut Clément ADER<BR>
&#9830; Présentation Mi-parcours Matetpro : 20/05/2015 Paris. <BR>
&#9830; Réunion T0+30 : 06/07/2015 à l’Institut Clément ADER<BR>
&#9830; Automne 2015 : Fabrication des éprouvettes et réalisation de 8 Essais VERTEX<BR>
&#9830; Réunion T0+36 : 04/02/2016 au LMT Cachan<BR>
&#9830; Printemps 2016 : Fabrication des éprouvettes et réalisation de 6 Essais VERTEX<BR>
&#9830; Réunion T0+42 : Avec Comité de Suivi : 14/09/2015 à l’Institut Clément ADER<BR>
&#9830; 16 Novembre 2016 : Soutenance de thèse de Joel Serra. <BR>
&#9830; 26 Novembre 2016 : Soutenance de thèse de Jean-Emmanuel Pierré.<BR>
<BR>
<BR>

 
<h1> Etapes Marquantes Fabrication et Validation Machine</h1>
<BR>
&#9830; 2012 : Elaboration cahier des charges, appel d’offre et sélection Contractant : SOGECLAIR Aerospace.<BR>
&#9830; Mars 2013 : Début Phase 1 Tranche ferme « pré-dimensionnement » machine d’essai.<BR>
&#9830; Juin 2013 : Fin Phase 1 Tranche ferme « pré-dimensionnement » machine d’essai.<BR>
&#9830; Juin 2013 : Début Phase 2 Tranche conditionnelle 1 « Dimensionnement et Conception» machine d’essai.<BR>
&#9830; Décembre 2013 : Fin Phase 2 Tranche conditionnelle 1 « Dimensionnement et Conception» machine d’essai.<BR>
&#9830; Février 2014 : Début Phase 3 Tranche conditionnelle 2 « Fabrication, montage et installation» machine d’essai.<BR>
&#9830; Octobre 2014 : Début installation et montage machine d’essai.<BR>
&#9830; Début Janvier 2015 : Fin du montage de la machine d’essai VERTEX.<BR>
&#9830; Fin Janvier 2015 : Formation QUIRI système de commande<BR>
&#9830; Février-Avril 2015 : Tests, Déverminage et Validation du montage.<BR> 
&#9830; Mai 2015 : Réception machine d’essai VERTEX.<BR>
<BR>

<br><br>";



?>
